version: "3.0"

services:
    database:
        container_name: rentx-database
        image: postgres:14.1-alpine
        ports:
        - "5432:5432"
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=docker
        - POSTGRES_DB="rentx_database"
        volumes:
        - ./.docker/database_data/:/var/lib/postgresql/data